# Generated by Django 5.1.6 on 2025-02-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='fecha',
            new_name='date',
        ),
    ]
